name: SAST with SonarCloud 5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_DEFAULT_VERSION: 20
  ANGULAR_CLI_VERSION: 17

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_DEFAULT_VERSION }} # Ensure it matches your application's version
        #cache: npm

    - name: Install dependencies
      run: npm ci

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}